name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
            
    - name: Build and push to deploy branch
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'emjrhys'
        reponame: 'css-pride-flags'
        gitemail: 'emjrhys@gmail.com'
        gitname: 'Emma Rhys'
        cname: 'cssprideflags.com'
        gitmsg: 'deploy'
        useyarn: true
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
