name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    - name: Update Yarn
      run: |
            npm install -g corepack
            corepack enable && \
            yarn init -2 && \
            yarn set version stable
    - name: Build Vue
      env:
        username: 'emjrhys'
        reponame: 'css-pride-flags'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      run: |
            YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
            ls
            yarn build
            cd dist
            ln -s index.html 404.html
            if [ "none" !=  ${{ inputs.cname }} ]; then echo '${{ inputs.cname }}' > CNAME; fi
            git config --global user.email "${{ inputs.gitemail }}"
            git config --global user.name "${{ inputs.gitname }}"
            git init
            git add -A
            git commit -m '${{ inputs.gitmsg }}'
            git push -f https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git master:main
      shell: bash
