name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
            
    - name: Build Vue
      env:
        username: 'emjrhys'
        reponame: 'css-pride-flags'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      run: |
            yarn install
            yarn build-only
            git add dist && git commit -m "building"
            git subtree push --prefix dist origin gh-pages
      shell: bash
